/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TokoFarda;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class dash_admin extends javax.swing.JFrame {

    /**
     * Creates new form tes1
     */
    public dash_admin() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        icons_admin = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        menuPanel = new javax.swing.JPanel();
        dashMenu = new javax.swing.JPanel();
        dashPanel = new javax.swing.JPanel();
        icons_dashboard = new javax.swing.JLabel();
        barangMenu = new javax.swing.JPanel();
        barangPanel = new javax.swing.JPanel();
        icons_barang = new javax.swing.JLabel();
        jenisBarang = new javax.swing.JPanel();
        jenisBarangPanel = new javax.swing.JPanel();
        icons_jenisBarang = new javax.swing.JLabel();
        supplierMenu = new javax.swing.JPanel();
        supplierPanel = new javax.swing.JPanel();
        icons_supplier = new javax.swing.JLabel();
        hutangMenu = new javax.swing.JPanel();
        hutangPanel = new javax.swing.JPanel();
        icons_hutang = new javax.swing.JLabel();
        supplayMenu = new javax.swing.JPanel();
        supplayPanel = new javax.swing.JPanel();
        icons_transkasi_supplay = new javax.swing.JLabel();
        jualMenu = new javax.swing.JPanel();
        jualPanel = new javax.swing.JPanel();
        icons_transaksi = new javax.swing.JLabel();
        transaksiMenu = new javax.swing.JPanel();
        transaksiPanel = new javax.swing.JPanel();
        icons_data_transaksi = new javax.swing.JLabel();
        userMenu = new javax.swing.JPanel();
        userPanel = new javax.swing.JPanel();
        icons_user = new javax.swing.JLabel();
        laporanMenu = new javax.swing.JPanel();
        laporanPanel = new javax.swing.JPanel();
        icons_laporan = new javax.swing.JLabel();
        logoutMenu = new javax.swing.JPanel();
        logoutPanel = new javax.swing.JPanel();
        icons_logout = new javax.swing.JLabel();
        mainMenu = new javax.swing.JPanel();
        dashAdmin1 = new TokoFarda.dashAdmin();
        menuBarang1 = new TokoFarda.menuDataBarang();
        menuJenisBarang1 = new TokoFarda.menuJenisBarang();
        menuDataSupplier1 = new TokoFarda.menuDataSupplier();
        menuDataUser1 = new TokoFarda.menuDataUser();
        menuTransaksiJual1 = new TokoFarda.menuTransaksiJual();
        menuTransaksiSupplay1 = new TokoFarda.menuTransaksiSupplay();
        menuDataTransaksi1 = new TokoFarda.menuDataTransaksi();
        menuLaporan1 = new TokoFarda.menuLaporan();
        menuDataHutang1 = new TokoFarda.menuDataHutang();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/icons.png")).getImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebarPanel.setBackground(new java.awt.Color(80, 151, 210));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(205, 100));

        logoPanel.setBackground(new java.awt.Color(80, 151, 210));

        icons_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/icons_admin.png"))); // NOI18N

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(icons_admin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoPanelLayout.createSequentialGroup()
                .addComponent(icons_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        menuPanel.setBackground(new java.awt.Color(80, 151, 210));
        menuPanel.setLayout(new java.awt.GridLayout(11, 1));

        dashMenu.setBackground(new java.awt.Color(80, 151, 210));

        dashPanel.setBackground(new java.awt.Color(80, 151, 210));

        icons_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        icons_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/25/icons_dashboard25.png"))); // NOI18N
        icons_dashboard.setText("Dashboard");
        icons_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icons_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icons_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icons_dashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icons_dashboardMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                icons_dashboardMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout dashPanelLayout = new javax.swing.GroupLayout(dashPanel);
        dashPanel.setLayout(dashPanelLayout);
        dashPanelLayout.setHorizontalGroup(
            dashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(icons_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashPanelLayout.setVerticalGroup(
            dashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(icons_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dashMenuLayout = new javax.swing.GroupLayout(dashMenu);
        dashMenu.setLayout(dashMenuLayout);
        dashMenuLayout.setHorizontalGroup(
            dashMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dashMenuLayout.setVerticalGroup(
            dashMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashMenuLayout.createSequentialGroup()
                .addComponent(dashPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        menuPanel.add(dashMenu);

        barangMenu.setBackground(new java.awt.Color(80, 151, 210));

        barangPanel.setBackground(new java.awt.Color(80, 151, 210));

        icons_barang.setForeground(new java.awt.Color(255, 255, 255));
        icons_barang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/25/icons_barang.png"))); // NOI18N
        icons_barang.setText("Data Barang");
        icons_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icons_barangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icons_barangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icons_barangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icons_barangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                icons_barangMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout barangPanelLayout = new javax.swing.GroupLayout(barangPanel);
        barangPanel.setLayout(barangPanelLayout);
        barangPanelLayout.setHorizontalGroup(
            barangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barangPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(icons_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        barangPanelLayout.setVerticalGroup(
            barangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icons_barang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout barangMenuLayout = new javax.swing.GroupLayout(barangMenu);
        barangMenu.setLayout(barangMenuLayout);
        barangMenuLayout.setHorizontalGroup(
            barangMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barangPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        barangMenuLayout.setVerticalGroup(
            barangMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barangMenuLayout.createSequentialGroup()
                .addComponent(barangPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        menuPanel.add(barangMenu);

        jenisBarang.setBackground(new java.awt.Color(80, 151, 210));

        jenisBarangPanel.setBackground(new java.awt.Color(80, 151, 210));

        icons_jenisBarang.setForeground(new java.awt.Color(255, 255, 255));
        icons_jenisBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/25/icon_jenisbarang 25.png"))); // NOI18N
        icons_jenisBarang.setText("Jenis Barang");
        icons_jenisBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icons_jenisBarangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icons_jenisBarangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icons_jenisBarangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icons_jenisBarangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                icons_jenisBarangMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jenisBarangPanelLayout = new javax.swing.GroupLayout(jenisBarangPanel);
        jenisBarangPanel.setLayout(jenisBarangPanelLayout);
        jenisBarangPanelLayout.setHorizontalGroup(
            jenisBarangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jenisBarangPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(icons_jenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jenisBarangPanelLayout.setVerticalGroup(
            jenisBarangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icons_jenisBarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jenisBarangLayout = new javax.swing.GroupLayout(jenisBarang);
        jenisBarang.setLayout(jenisBarangLayout);
        jenisBarangLayout.setHorizontalGroup(
            jenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jenisBarangPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jenisBarangLayout.setVerticalGroup(
            jenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jenisBarangLayout.createSequentialGroup()
                .addComponent(jenisBarangPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        menuPanel.add(jenisBarang);

        supplierMenu.setBackground(new java.awt.Color(80, 151, 210));

        supplierPanel.setBackground(new java.awt.Color(80, 151, 210));

        icons_supplier.setForeground(new java.awt.Color(255, 255, 255));
        icons_supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/25/icons_supplier.png"))); // NOI18N
        icons_supplier.setText("Data Supplier");
        icons_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icons_supplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icons_supplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icons_supplierMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icons_supplierMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                icons_supplierMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout supplierPanelLayout = new javax.swing.GroupLayout(supplierPanel);
        supplierPanel.setLayout(supplierPanelLayout);
        supplierPanelLayout.setHorizontalGroup(
            supplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, supplierPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(icons_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        supplierPanelLayout.setVerticalGroup(
            supplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, supplierPanelLayout.createSequentialGroup()
                .addComponent(icons_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout supplierMenuLayout = new javax.swing.GroupLayout(supplierMenu);
        supplierMenu.setLayout(supplierMenuLayout);
        supplierMenuLayout.setHorizontalGroup(
            supplierMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(supplierPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        supplierMenuLayout.setVerticalGroup(
            supplierMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierMenuLayout.createSequentialGroup()
                .addComponent(supplierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        menuPanel.add(supplierMenu);

        hutangMenu.setBackground(new java.awt.Color(80, 151, 210));

        hutangPanel.setBackground(new java.awt.Color(80, 151, 210));

        icons_hutang.setForeground(new java.awt.Color(255, 255, 255));
        icons_hutang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/25/icons_hutang25.png"))); // NOI18N
        icons_hutang.setText("Data Hutang");
        icons_hutang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icons_hutangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icons_hutangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icons_hutangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icons_hutangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                icons_hutangMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout hutangPanelLayout = new javax.swing.GroupLayout(hutangPanel);
        hutangPanel.setLayout(hutangPanelLayout);
        hutangPanelLayout.setHorizontalGroup(
            hutangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hutangPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(icons_hutang, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        hutangPanelLayout.setVerticalGroup(
            hutangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hutangPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(icons_hutang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout hutangMenuLayout = new javax.swing.GroupLayout(hutangMenu);
        hutangMenu.setLayout(hutangMenuLayout);
        hutangMenuLayout.setHorizontalGroup(
            hutangMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hutangPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        hutangMenuLayout.setVerticalGroup(
            hutangMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hutangMenuLayout.createSequentialGroup()
                .addComponent(hutangPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        menuPanel.add(hutangMenu);

        supplayMenu.setBackground(new java.awt.Color(80, 151, 210));

        supplayPanel.setBackground(new java.awt.Color(80, 151, 210));

        icons_transkasi_supplay.setForeground(new java.awt.Color(255, 255, 255));
        icons_transkasi_supplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/25/icons_transaksi_supplay25.png"))); // NOI18N
        icons_transkasi_supplay.setText("Transaksi Supplay");
        icons_transkasi_supplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icons_transkasi_supplayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icons_transkasi_supplayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icons_transkasi_supplayMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icons_transkasi_supplayMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                icons_transkasi_supplayMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout supplayPanelLayout = new javax.swing.GroupLayout(supplayPanel);
        supplayPanel.setLayout(supplayPanelLayout);
        supplayPanelLayout.setHorizontalGroup(
            supplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, supplayPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(icons_transkasi_supplay, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        supplayPanelLayout.setVerticalGroup(
            supplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icons_transkasi_supplay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout supplayMenuLayout = new javax.swing.GroupLayout(supplayMenu);
        supplayMenu.setLayout(supplayMenuLayout);
        supplayMenuLayout.setHorizontalGroup(
            supplayMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(supplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        supplayMenuLayout.setVerticalGroup(
            supplayMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplayMenuLayout.createSequentialGroup()
                .addComponent(supplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        menuPanel.add(supplayMenu);

        jualMenu.setBackground(new java.awt.Color(80, 151, 210));

        jualPanel.setBackground(new java.awt.Color(80, 151, 210));

        icons_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        icons_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/25/icons_transaksi25.png"))); // NOI18N
        icons_transaksi.setText("Transaksi Jual");
        icons_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icons_transaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icons_transaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icons_transaksiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icons_transaksiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                icons_transaksiMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jualPanelLayout = new javax.swing.GroupLayout(jualPanel);
        jualPanel.setLayout(jualPanelLayout);
        jualPanelLayout.setHorizontalGroup(
            jualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jualPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(icons_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jualPanelLayout.setVerticalGroup(
            jualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jualPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(icons_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jualMenuLayout = new javax.swing.GroupLayout(jualMenu);
        jualMenu.setLayout(jualMenuLayout);
        jualMenuLayout.setHorizontalGroup(
            jualMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jualPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jualMenuLayout.setVerticalGroup(
            jualMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jualMenuLayout.createSequentialGroup()
                .addComponent(jualPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        menuPanel.add(jualMenu);

        transaksiMenu.setBackground(new java.awt.Color(80, 151, 210));

        transaksiPanel.setBackground(new java.awt.Color(80, 151, 210));

        icons_data_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        icons_data_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/25/icons_book25.png"))); // NOI18N
        icons_data_transaksi.setText("Data Transaksi");
        icons_data_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icons_data_transaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icons_data_transaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icons_data_transaksiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icons_data_transaksiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                icons_data_transaksiMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout transaksiPanelLayout = new javax.swing.GroupLayout(transaksiPanel);
        transaksiPanel.setLayout(transaksiPanelLayout);
        transaksiPanelLayout.setHorizontalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaksiPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(icons_data_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        transaksiPanelLayout.setVerticalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(icons_data_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout transaksiMenuLayout = new javax.swing.GroupLayout(transaksiMenu);
        transaksiMenu.setLayout(transaksiMenuLayout);
        transaksiMenuLayout.setHorizontalGroup(
            transaksiMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transaksiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        transaksiMenuLayout.setVerticalGroup(
            transaksiMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiMenuLayout.createSequentialGroup()
                .addComponent(transaksiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        menuPanel.add(transaksiMenu);

        userMenu.setBackground(new java.awt.Color(80, 151, 210));

        userPanel.setBackground(new java.awt.Color(80, 151, 210));

        icons_user.setForeground(new java.awt.Color(255, 255, 255));
        icons_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/25/icons_user25.png"))); // NOI18N
        icons_user.setText("Data User");
        icons_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icons_userMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icons_userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icons_userMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icons_userMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                icons_userMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(icons_user, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(icons_user, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout userMenuLayout = new javax.swing.GroupLayout(userMenu);
        userMenu.setLayout(userMenuLayout);
        userMenuLayout.setHorizontalGroup(
            userMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        userMenuLayout.setVerticalGroup(
            userMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMenuLayout.createSequentialGroup()
                .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        menuPanel.add(userMenu);

        laporanMenu.setBackground(new java.awt.Color(80, 151, 210));

        laporanPanel.setBackground(new java.awt.Color(80, 151, 210));

        icons_laporan.setForeground(new java.awt.Color(255, 255, 255));
        icons_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/25/icons_laporan25.png"))); // NOI18N
        icons_laporan.setText("Data Laporan");
        icons_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icons_laporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icons_laporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icons_laporanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icons_laporanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                icons_laporanMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout laporanPanelLayout = new javax.swing.GroupLayout(laporanPanel);
        laporanPanel.setLayout(laporanPanelLayout);
        laporanPanelLayout.setHorizontalGroup(
            laporanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporanPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(icons_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        laporanPanelLayout.setVerticalGroup(
            laporanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(icons_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout laporanMenuLayout = new javax.swing.GroupLayout(laporanMenu);
        laporanMenu.setLayout(laporanMenuLayout);
        laporanMenuLayout.setHorizontalGroup(
            laporanMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(laporanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        laporanMenuLayout.setVerticalGroup(
            laporanMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanMenuLayout.createSequentialGroup()
                .addComponent(laporanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        menuPanel.add(laporanMenu);

        logoutMenu.setBackground(new java.awt.Color(80, 151, 210));

        logoutPanel.setBackground(new java.awt.Color(80, 151, 210));

        icons_logout.setForeground(new java.awt.Color(255, 255, 255));
        icons_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/25/icons_logout.png"))); // NOI18N
        icons_logout.setText("Logout");
        icons_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icons_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icons_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icons_logoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icons_logoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                icons_logoutMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout logoutPanelLayout = new javax.swing.GroupLayout(logoutPanel);
        logoutPanel.setLayout(logoutPanelLayout);
        logoutPanelLayout.setHorizontalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(icons_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        logoutPanelLayout.setVerticalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(icons_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout logoutMenuLayout = new javax.swing.GroupLayout(logoutMenu);
        logoutMenu.setLayout(logoutMenuLayout);
        logoutMenuLayout.setHorizontalGroup(
            logoutMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        logoutMenuLayout.setVerticalGroup(
            logoutMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutMenuLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuPanel.add(logoutMenu);

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
        );

        getContentPane().add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 746));

        mainMenu.setBackground(new java.awt.Color(207, 212, 220));
        mainMenu.setLayout(new java.awt.CardLayout());
        mainMenu.add(dashAdmin1, "card1");
        mainMenu.add(menuBarang1, "card2");
        mainMenu.add(menuJenisBarang1, "card10");
        mainMenu.add(menuDataSupplier1, "card3");
        mainMenu.add(menuDataUser1, "card4");
        mainMenu.add(menuTransaksiJual1, "card6");
        mainMenu.add(menuTransaksiSupplay1, "card7");
        mainMenu.add(menuDataTransaksi1, "card8");
        mainMenu.add(menuLaporan1, "card9");
        mainMenu.add(menuDataHutang1, "card11");

        getContentPane().add(mainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1170, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void icons_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_dashboardMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) mainMenu.getLayout();
        cl.show(mainMenu,"card1");
    }//GEN-LAST:event_icons_dashboardMouseClicked

    private void icons_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_barangMouseClicked
        CardLayout cl = (CardLayout) mainMenu.getLayout();
        cl.show(mainMenu, "card2");
        
        menuDataBarang card2 = (menuDataBarang) mainMenu.getComponent(1); 
        card2.getData();
        card2.namaSupplier();
        card2.jenisBarang();
    }//GEN-LAST:event_icons_barangMouseClicked

    private void icons_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_supplierMouseClicked
        // TODO add your handling code here:
        
        CardLayout cl = (CardLayout) mainMenu.getLayout();
        cl.show(mainMenu, "card3");
    }//GEN-LAST:event_icons_supplierMouseClicked

    private void icons_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_userMouseClicked
        // TODO add your handling code here:
        
        CardLayout cl = (CardLayout) mainMenu.getLayout();
        cl.show(mainMenu, "card4");
    }//GEN-LAST:event_icons_userMouseClicked

    private void icons_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_logoutMouseClicked
        // TODO add your handling code here:

        if(JOptionPane.showConfirmDialog(this, "Apakah Anda Mau Logout ?", "Konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            form_login lgn = new form_login();
            lgn.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_icons_logoutMouseClicked

    private void icons_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_transaksiMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) mainMenu.getLayout();
        cl.show(mainMenu, "card6");
        
        menuTransaksiJual card6 = (menuTransaksiJual) mainMenu.getComponent(5); 
        card6.getData();
    }//GEN-LAST:event_icons_transaksiMouseClicked

    private void icons_transkasi_supplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_transkasi_supplayMouseClicked
        // TODO add your handling code here:
        
        CardLayout cl = (CardLayout) mainMenu.getLayout();
        cl.show(mainMenu, "card7");
        
        menuTransaksiSupplay card7 = (menuTransaksiSupplay) mainMenu.getComponent(6); 
        card7.getData();
    }//GEN-LAST:event_icons_transkasi_supplayMouseClicked

    private void icons_data_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_data_transaksiMouseClicked
        // TODO add your handling code here:
        
        CardLayout cl = (CardLayout) mainMenu.getLayout();
        cl.show(mainMenu, "card8");
        
        menuDataTransaksi card8 = (menuDataTransaksi) mainMenu.getComponent(7); 
        card8.getDataJual();
        card8.getDataBeli();
    }//GEN-LAST:event_icons_data_transaksiMouseClicked

    private void icons_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_laporanMouseClicked
        // TODO add your handling code here:
        
        CardLayout cl = (CardLayout) mainMenu.getLayout();
        cl.show(mainMenu, "card9");
    }//GEN-LAST:event_icons_laporanMouseClicked

    private void icons_jenisBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_jenisBarangMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) mainMenu.getLayout();
        cl.show(mainMenu, "card10");
        
        menuJenisBarang card10 = (menuJenisBarang) mainMenu.getComponent(2); 
        card10.getData();
    }//GEN-LAST:event_icons_jenisBarangMouseClicked

    private void icons_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_dashboardMouseEntered
        // TODO add your handling code here:
        dashPanel.setBackground(new Color(162, 188, 224));
    }//GEN-LAST:event_icons_dashboardMouseEntered

    private void icons_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_dashboardMouseExited
        // TODO add your handling code here:
        dashPanel.setBackground(new Color(82, 153, 211));
    }//GEN-LAST:event_icons_dashboardMouseExited

    private void icons_dashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_dashboardMousePressed
        // TODO add your handling code here:
        dashPanel.setBackground(new Color(143, 164, 195));
    }//GEN-LAST:event_icons_dashboardMousePressed

    private void icons_dashboardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_dashboardMouseReleased
        // TODO add your handling code here:
        dashPanel.setBackground(new Color(162, 188, 224));
    }//GEN-LAST:event_icons_dashboardMouseReleased

    private void icons_barangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_barangMouseEntered
        // TODO add your handling code here:
        barangPanel.setBackground(new Color(162, 188, 224));
    }//GEN-LAST:event_icons_barangMouseEntered

    private void icons_barangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_barangMouseExited
        // TODO add your handling code here:
        barangPanel.setBackground(new Color(82, 153, 211));
    }//GEN-LAST:event_icons_barangMouseExited

    private void icons_barangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_barangMousePressed
        // TODO add your handling code here:
        barangPanel.setBackground(new Color(143, 164, 195));
    }//GEN-LAST:event_icons_barangMousePressed

    private void icons_barangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_barangMouseReleased
        // TODO add your handling code here:
        barangPanel.setBackground(new Color(162, 188, 224));
    }//GEN-LAST:event_icons_barangMouseReleased

    private void icons_jenisBarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_jenisBarangMouseEntered
        // TODO add your handling code here:
        jenisBarangPanel.setBackground(new Color(162, 188, 224));
    }//GEN-LAST:event_icons_jenisBarangMouseEntered

    private void icons_jenisBarangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_jenisBarangMouseExited
        // TODO add your handling code here:
        jenisBarangPanel.setBackground(new Color(82, 153, 211));
    }//GEN-LAST:event_icons_jenisBarangMouseExited

    private void icons_jenisBarangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_jenisBarangMousePressed
        // TODO add your handling code here:
        jenisBarangPanel.setBackground(new Color(143, 164, 195));
    }//GEN-LAST:event_icons_jenisBarangMousePressed

    private void icons_jenisBarangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_jenisBarangMouseReleased
        // TODO add your handling code here:
        jenisBarangPanel.setBackground(new Color(162, 188, 224));
    }//GEN-LAST:event_icons_jenisBarangMouseReleased

    private void icons_supplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_supplierMouseEntered
        // TODO add your handling code here:
        supplierPanel.setBackground(new Color(162, 188, 224));
    }//GEN-LAST:event_icons_supplierMouseEntered

    private void icons_supplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_supplierMouseExited
        // TODO add your handling code here:
        supplierPanel.setBackground(new Color(82, 153, 211));
    }//GEN-LAST:event_icons_supplierMouseExited

    private void icons_supplierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_supplierMousePressed
        // TODO add your handling code here:
        supplierPanel.setBackground(new Color(143, 164, 195));
    }//GEN-LAST:event_icons_supplierMousePressed

    private void icons_supplierMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_supplierMouseReleased
        // TODO add your handling code here:
        supplierPanel.setBackground(new Color(162, 188, 224));
    }//GEN-LAST:event_icons_supplierMouseReleased

    private void icons_hutangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_hutangMouseEntered
        // TODO add your handling code here:
        hutangPanel.setBackground(new Color(162, 188, 224));
    }//GEN-LAST:event_icons_hutangMouseEntered

    private void icons_hutangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_hutangMouseExited
        // TODO add your handling code here:
        hutangPanel.setBackground(new Color(82, 153, 211));
    }//GEN-LAST:event_icons_hutangMouseExited

    private void icons_hutangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_hutangMousePressed
        // TODO add your handling code here:
        hutangPanel.setBackground(new Color(143, 164, 195));
    }//GEN-LAST:event_icons_hutangMousePressed

    private void icons_hutangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_hutangMouseReleased
        // TODO add your handling code here:
        hutangPanel.setBackground(new Color(162, 188, 224));
    }//GEN-LAST:event_icons_hutangMouseReleased

    private void icons_transkasi_supplayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_transkasi_supplayMouseEntered
        // TODO add your handling code here:
        supplayPanel.setBackground(new Color(162, 188, 224));
    }//GEN-LAST:event_icons_transkasi_supplayMouseEntered

    private void icons_transkasi_supplayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_transkasi_supplayMouseExited
        // TODO add your handling code here:
        supplayPanel.setBackground(new Color(82, 153, 211));
    }//GEN-LAST:event_icons_transkasi_supplayMouseExited

    private void icons_transkasi_supplayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_transkasi_supplayMousePressed
        // TODO add your handling code here:
        supplayPanel.setBackground(new Color(143, 164, 195));
    }//GEN-LAST:event_icons_transkasi_supplayMousePressed

    private void icons_transkasi_supplayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_transkasi_supplayMouseReleased
        // TODO add your handling code here:
        supplayPanel.setBackground(new Color(162, 188, 224));
    }//GEN-LAST:event_icons_transkasi_supplayMouseReleased

    private void icons_transaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_transaksiMouseEntered
        // TODO add your handling code here:
        jualPanel.setBackground(new Color(162, 188, 224));
    }//GEN-LAST:event_icons_transaksiMouseEntered

    private void icons_transaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_transaksiMouseExited
        // TODO add your handling code here:
        jualPanel.setBackground(new Color(82, 153, 211));
    }//GEN-LAST:event_icons_transaksiMouseExited

    private void icons_transaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_transaksiMousePressed
        // TODO add your handling code here:
        jualPanel.setBackground(new Color(143, 164, 195));
    }//GEN-LAST:event_icons_transaksiMousePressed

    private void icons_transaksiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_transaksiMouseReleased
        // TODO add your handling code here:
        jualPanel.setBackground(new Color(162, 188, 224));
    }//GEN-LAST:event_icons_transaksiMouseReleased

    private void icons_data_transaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_data_transaksiMouseEntered
        // TODO add your handling code here:
        transaksiPanel.setBackground(new Color(162, 188, 224));
    }//GEN-LAST:event_icons_data_transaksiMouseEntered

    private void icons_data_transaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_data_transaksiMouseExited
        // TODO add your handling code here:
        transaksiPanel.setBackground(new Color(82, 153, 211));
    }//GEN-LAST:event_icons_data_transaksiMouseExited

    private void icons_data_transaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_data_transaksiMousePressed
        // TODO add your handling code here:
        transaksiPanel.setBackground(new Color(143, 164, 195));
    }//GEN-LAST:event_icons_data_transaksiMousePressed

    private void icons_data_transaksiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_data_transaksiMouseReleased
        // TODO add your handling code here:
        transaksiPanel.setBackground(new Color(162, 188, 224));
    }//GEN-LAST:event_icons_data_transaksiMouseReleased

    private void icons_userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_userMouseEntered
        // TODO add your handling code here:
        userPanel.setBackground(new Color(162, 188, 224));
    }//GEN-LAST:event_icons_userMouseEntered

    private void icons_userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_userMouseExited
        // TODO add your handling code here:
        userPanel.setBackground(new Color(82, 153, 211));
    }//GEN-LAST:event_icons_userMouseExited

    private void icons_userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_userMousePressed
        // TODO add your handling code here:
        userPanel.setBackground(new Color(143, 164, 195));
    }//GEN-LAST:event_icons_userMousePressed

    private void icons_userMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_userMouseReleased
        // TODO add your handling code here:
        userPanel.setBackground(new Color(162, 188, 224));
    }//GEN-LAST:event_icons_userMouseReleased

    private void icons_laporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_laporanMouseEntered
        // TODO add your handling code here:
        laporanPanel.setBackground(new Color(162, 188, 224));
    }//GEN-LAST:event_icons_laporanMouseEntered

    private void icons_laporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_laporanMouseExited
        // TODO add your handling code here:
        laporanPanel.setBackground(new Color(82, 153, 211));
    }//GEN-LAST:event_icons_laporanMouseExited

    private void icons_laporanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_laporanMousePressed
        // TODO add your handling code here:
        laporanPanel.setBackground(new Color(143, 164, 195));
    }//GEN-LAST:event_icons_laporanMousePressed

    private void icons_laporanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_laporanMouseReleased
        // TODO add your handling code here:
        laporanPanel.setBackground(new Color(162, 188, 224));
    }//GEN-LAST:event_icons_laporanMouseReleased

    private void icons_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_logoutMouseEntered
        // TODO add your handling code here:
        logoutPanel.setBackground(new Color(162, 188, 224));
    }//GEN-LAST:event_icons_logoutMouseEntered

    private void icons_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_logoutMouseExited
        // TODO add your handling code here:
        logoutPanel.setBackground(new Color(82, 153, 211));
    }//GEN-LAST:event_icons_logoutMouseExited

    private void icons_logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_logoutMousePressed
        // TODO add your handling code here:
        logoutPanel.setBackground(new Color(143, 164, 195));
    }//GEN-LAST:event_icons_logoutMousePressed

    private void icons_logoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_logoutMouseReleased
        // TODO add your handling code here:
        logoutPanel.setBackground(new Color(162, 188, 224));
    }//GEN-LAST:event_icons_logoutMouseReleased

    private void icons_hutangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icons_hutangMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) mainMenu.getLayout();
        cl.show(mainMenu, "card11");
        
        menuDataHutang card11 = (menuDataHutang) mainMenu.getComponent(9); 
        card11.getData();
    }//GEN-LAST:event_icons_hutangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dash_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dash_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dash_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dash_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dash_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barangMenu;
    private javax.swing.JPanel barangPanel;
    private TokoFarda.dashAdmin dashAdmin1;
    private javax.swing.JPanel dashMenu;
    private javax.swing.JPanel dashPanel;
    private javax.swing.JPanel hutangMenu;
    private javax.swing.JPanel hutangPanel;
    private javax.swing.JLabel icons_admin;
    private javax.swing.JLabel icons_barang;
    private javax.swing.JLabel icons_dashboard;
    private javax.swing.JLabel icons_data_transaksi;
    private javax.swing.JLabel icons_hutang;
    private javax.swing.JLabel icons_jenisBarang;
    private javax.swing.JLabel icons_laporan;
    private javax.swing.JLabel icons_logout;
    private javax.swing.JLabel icons_supplier;
    private javax.swing.JLabel icons_transaksi;
    private javax.swing.JLabel icons_transkasi_supplay;
    private javax.swing.JLabel icons_user;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jenisBarang;
    private javax.swing.JPanel jenisBarangPanel;
    private javax.swing.JPanel jualMenu;
    private javax.swing.JPanel jualPanel;
    private javax.swing.JPanel laporanMenu;
    private javax.swing.JPanel laporanPanel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel logoutMenu;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JPanel mainMenu;
    private TokoFarda.menuDataBarang menuBarang1;
    private TokoFarda.menuDataHutang menuDataHutang1;
    private TokoFarda.menuDataSupplier menuDataSupplier1;
    private TokoFarda.menuDataTransaksi menuDataTransaksi1;
    private TokoFarda.menuDataUser menuDataUser1;
    private TokoFarda.menuJenisBarang menuJenisBarang1;
    private TokoFarda.menuLaporan menuLaporan1;
    private javax.swing.JPanel menuPanel;
    private TokoFarda.menuTransaksiJual menuTransaksiJual1;
    private TokoFarda.menuTransaksiSupplay menuTransaksiSupplay1;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JPanel supplayMenu;
    private javax.swing.JPanel supplayPanel;
    private javax.swing.JPanel supplierMenu;
    private javax.swing.JPanel supplierPanel;
    private javax.swing.JPanel transaksiMenu;
    private javax.swing.JPanel transaksiPanel;
    private javax.swing.JPanel userMenu;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
