/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TokoFarda;

/**
 *
 * @author user
 */
public class data_hutang extends javax.swing.JFrame {

    /**
     * Creates new form data_hutang
     */
    public data_hutang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        icons_admin = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        icons_dashboard = new javax.swing.JLabel();
        icons_barang = new javax.swing.JLabel();
        icons_supplier = new javax.swing.JLabel();
        icons_hutang = new javax.swing.JLabel();
        icons_transkasi_supplay = new javax.swing.JLabel();
        icons_transaksi = new javax.swing.JLabel();
        icons_data_transaksi = new javax.swing.JLabel();
        icons_user = new javax.swing.JLabel();
        icons_laporan = new javax.swing.JLabel();
        icons_logout = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Nama_supplier = new javax.swing.JLabel();
        nama_supplier = new javax.swing.JTextField();
        No_telepon = new javax.swing.JLabel();
        no_telepon = new javax.swing.JTextField();
        Alamat = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        Jumlah_hutang = new javax.swing.JLabel();
        jumlah_hutang = new javax.swing.JTextField();
        Tenggat_bayar = new javax.swing.JLabel();
        tenggat_bayar = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        tambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(80, 151, 210));

        icons_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/icons_admin.png"))); // NOI18N

        icons_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        icons_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/25/icons_dashboard25.png"))); // NOI18N
        icons_dashboard.setText("Dashboard");

        icons_barang.setForeground(new java.awt.Color(255, 255, 255));
        icons_barang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/25/icons_barang.png"))); // NOI18N
        icons_barang.setText("Data Barang");

        icons_supplier.setForeground(new java.awt.Color(255, 255, 255));
        icons_supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/25/icons_supplier.png"))); // NOI18N
        icons_supplier.setText("Data Supplier");

        icons_hutang.setForeground(new java.awt.Color(255, 255, 255));
        icons_hutang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/25/icons_hutang25.png"))); // NOI18N
        icons_hutang.setText("Data Hutang");

        icons_transkasi_supplay.setForeground(new java.awt.Color(255, 255, 255));
        icons_transkasi_supplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/25/icons_transaksi_supplay25.png"))); // NOI18N
        icons_transkasi_supplay.setText("Transaksi Supplay");

        icons_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        icons_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/25/icons_transaksi25.png"))); // NOI18N
        icons_transaksi.setText("Transaksi Jual");

        icons_data_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        icons_data_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/25/icons_book25.png"))); // NOI18N
        icons_data_transaksi.setText("Data Transaksi");

        icons_user.setForeground(new java.awt.Color(255, 255, 255));
        icons_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/25/icons_user25.png"))); // NOI18N
        icons_user.setText("Data User");

        icons_laporan.setForeground(new java.awt.Color(255, 255, 255));
        icons_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/25/icons_laporan25.png"))); // NOI18N
        icons_laporan.setText("Data Laporan");

        icons_logout.setForeground(new java.awt.Color(255, 255, 255));
        icons_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/DashAdmin/25/icons_logout.png"))); // NOI18N
        icons_logout.setText("Logout");

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(icons_admin))
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(icons_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(icons_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(icons_barang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(icons_supplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(icons_hutang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(icons_transkasi_supplay, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(icons_transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(icons_data_transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(icons_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(icons_laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(icons_admin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icons_dashboard)
                .addGap(18, 18, 18)
                .addComponent(icons_barang)
                .addGap(18, 18, 18)
                .addComponent(icons_supplier)
                .addGap(18, 18, 18)
                .addComponent(icons_hutang)
                .addGap(18, 18, 18)
                .addComponent(icons_transkasi_supplay)
                .addGap(18, 18, 18)
                .addComponent(icons_transaksi)
                .addGap(18, 18, 18)
                .addComponent(icons_data_transaksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(icons_user)
                .addGap(18, 18, 18)
                .addComponent(icons_laporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(icons_logout)
                .addGap(22, 22, 22))
        );

        getContentPane().add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 750));

        background.setBackground(new java.awt.Color(207, 212, 220));

        header.setBackground(new java.awt.Color(237, 237, 237));

        title.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        title.setText("Tabel Data Hutang");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(title)
                .addContainerGap(1043, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(title)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        footer.setBackground(new java.awt.Color(237, 237, 237));

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1260, Short.MAX_VALUE)
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Nama_supplier.setText("Nama Supplier");

        No_telepon.setText("No Telepon");

        Alamat.setText("Alamat");

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane2.setViewportView(alamat);

        Jumlah_hutang.setText("Jumlah Hutang");

        jumlah_hutang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_hutangActionPerformed(evt);
            }
        });

        Tenggat_bayar.setText("Tenggat Bayar");

        tenggat_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenggat_bayarActionPerformed(evt);
            }
        });

        edit.setText("Edit");

        hapus.setText("Hapus");

        refresh.setText("Refresh");

        tambah.setText("Tambah");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Nama_supplier)
                    .addComponent(No_telepon)
                    .addComponent(Alamat)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(edit)
                        .addGap(18, 18, 18)
                        .addComponent(hapus)
                        .addGap(18, 18, 18)
                        .addComponent(refresh)
                        .addGap(18, 18, 18)
                        .addComponent(tambah))
                    .addComponent(Jumlah_hutang)
                    .addComponent(nama_supplier)
                    .addComponent(jumlah_hutang)
                    .addComponent(no_telepon)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .addComponent(Tenggat_bayar)
                    .addComponent(tenggat_bayar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Nama_supplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nama_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(No_telepon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(no_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Alamat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Jumlah_hutang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jumlah_hutang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Tenggat_bayar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tenggat_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edit)
                            .addComponent(hapus)
                            .addComponent(refresh)
                            .addComponent(tambah))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 1260, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jumlah_hutangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_hutangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah_hutangActionPerformed

    private void tenggat_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenggat_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenggat_bayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_hutang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_hutang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_hutang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_hutang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_hutang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel Jumlah_hutang;
    private javax.swing.JLabel Nama_supplier;
    private javax.swing.JLabel No_telepon;
    private javax.swing.JLabel Tenggat_bayar;
    private javax.swing.JTextArea alamat;
    private javax.swing.JPanel background;
    private javax.swing.JButton edit;
    private javax.swing.JPanel footer;
    private javax.swing.JButton hapus;
    private javax.swing.JPanel header;
    private javax.swing.JLabel icons_admin;
    private javax.swing.JLabel icons_barang;
    private javax.swing.JLabel icons_dashboard;
    private javax.swing.JLabel icons_data_transaksi;
    private javax.swing.JLabel icons_hutang;
    private javax.swing.JLabel icons_laporan;
    private javax.swing.JLabel icons_logout;
    private javax.swing.JLabel icons_supplier;
    private javax.swing.JLabel icons_transaksi;
    private javax.swing.JLabel icons_transkasi_supplay;
    private javax.swing.JLabel icons_user;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jumlah_hutang;
    private javax.swing.JTextField nama_supplier;
    private javax.swing.JTextField no_telepon;
    private javax.swing.JButton refresh;
    private javax.swing.JPanel sidebar;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField tenggat_bayar;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
