package TokoFarda;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.Cursor;
import java.sql.*;
import javax.swing.*;

public class form_login extends javax.swing.JFrame {
    int xx, xy;
    
    Connection conn = null; //Mengambil variabel conn berjenis Connection untuk koneksi
    ResultSet rs = null; //Variabel untuk menampilkan hasil query
    PreparedStatement pst = null; //Varibel untuk menampung query yang akan dieksekusi
    public form_login() {
        initComponents();
        conn = Koneksi.Koneksi.KoneksiDB();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_close = new javax.swing.JLabel();
        icon_username = new javax.swing.JLabel();
        icon_lock = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btn_login = new rojerusan.RSMaterialButtonRectangle();
        lupaPassword = new javax.swing.JLabel();
        formLogin = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        bg_toko = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/Login/icons_exit.png"))); // NOI18N
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, -1));

        icon_username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/Login/icons_username25.png"))); // NOI18N
        getContentPane().add(icon_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, -1, 40));

        icon_lock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/Login/icons_lock.png"))); // NOI18N
        getContentPane().add(icon_lock, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, -1, 30));

        txt_username.setBackground(new java.awt.Color(235, 229, 213));
        txt_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_username.setText("Username");
        txt_username.setBorder(null);
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 250, 40));

        txt_password.setBackground(new java.awt.Color(235, 229, 213));
        txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_password.setText("Password");
        txt_password.setBorder(null);
        txt_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_passwordFocusLost(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 250, 30));

        btn_login.setBackground(new java.awt.Color(183, 213, 224));
        btn_login.setForeground(new java.awt.Color(0, 0, 0));
        btn_login.setText("login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 290, 50));

        lupaPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lupaPassword.setText("Lupa Password?");
        lupaPassword.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lupaPasswordMouseMoved(evt);
            }
        });
        lupaPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lupaPasswordMouseClicked(evt);
            }
        });
        getContentPane().add(lupaPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, -1, -1));

        formLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/Login/formLogin.png"))); // NOI18N
        getContentPane().add(formLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, -1));

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/Login/title.png"))); // NOI18N
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bg_toko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/Login/bg_toko.png"))); // NOI18N
        getContentPane().add(bg_toko, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mockup/Login/background.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getX();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
        String username = txt_username.getText();
        if(username.equals("")||username.equals("Username")){
            txt_username.setText("Username");
        }
    }//GEN-LAST:event_txt_usernameFocusLost

    private void txt_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusGained
        String username = txt_username.getText();
        if(username.equals("Username")){
            txt_username.setText("");
        }
    }//GEN-LAST:event_txt_usernameFocusGained

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        if (JOptionPane.showConfirmDialog(this, "Exit Program ?", "Konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed

        String id;
        String namaUser;
        String role;
        
        String sql = "select * from user where Username=? AND Password=?";
        
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_username.getText());
            pst.setString(2, txt_password.getText());
            
            rs = pst.executeQuery();
            if (rs.next()){
                id = rs.getString("Id_user");
                namaUser = rs.getString("Nama_User");
                role = rs.getString("Level");
                
                session.setU_id(id);
                session.setU_Username(namaUser);
                session.setU_email(role);
                if(rs.getString("Level").equals("Admin")){
                    dash_admin adm = new dash_admin();
                    adm.setVisible(true);
                    adm.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    this.setVisible(false);
                }
                if(rs.getString("Level").equals("Kasir")) {
                    dash_kasir ksr = new dash_kasir();
                    ksr.setVisible(true);
                    ksr.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    this.setVisible(false);
                }
                if(rs.getString("Level").equals("Owner")) {
                    dash_owner own = new dash_owner();
                    own.setVisible(true);
                    own.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    this.setVisible(false);
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "Username and Password is INCORRECT");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void txt_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusGained
        String password = txt_password.getText();
        if(password.equals("Password")){
            txt_password.setText("");
        }
    }//GEN-LAST:event_txt_passwordFocusGained

    private void txt_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusLost
        String password = txt_password.getText();
        if(password.equals("")||password.equals("Password")){
            txt_password.setText("Password");
        }
    }//GEN-LAST:event_txt_passwordFocusLost

    private void lupaPasswordMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaPasswordMouseMoved
        // TODO add your handling code here:
        lupaPassword.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lupaPasswordMouseMoved

    private void lupaPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lupaPasswordMouseClicked
        // TODO add your handling code here:
        String email = JOptionPane.showInputDialog(null, "Masukkan alamat email", "Lupa Password", JOptionPane.PLAIN_MESSAGE);
        
        String sql = "select * from user where Email=?";
        
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, email);
            rs = pst.executeQuery();
            if(rs.next()){
                session.setEmail(email);
                JTextField jawabanField = new JTextField();
                Object[] message = {
                    "Pertanyaan keamanan:", 
                    "Berapa nomor toko?",
                    "Jawaban:", jawabanField
                };
                int option = JOptionPane.showConfirmDialog(null, message, "Lupa Password", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
                    String jawabanKeamanan = jawabanField.getText();

                    if (jawabanKeamanan.equals("192.168.58.1")) {
                        JOptionPane.showMessageDialog(null, "Jawaban keamanan cocok, Anda dapat mengatur password baru");
                        resetCode rc = new resetCode();
                        rc.setVisible(true);
                        rc.setLocationRelativeTo(null);
                        rc.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
                    } else {
                        JOptionPane.showMessageDialog(null, "Jawaban keamanan tidak cocok");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Alamat email tidak ditemnukan");
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_lupaPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel bg_toko;
    private javax.swing.JLabel btn_close;
    private rojerusan.RSMaterialButtonRectangle btn_login;
    private javax.swing.JLabel formLogin;
    private javax.swing.JLabel icon_lock;
    private javax.swing.JLabel icon_username;
    private javax.swing.JLabel lupaPassword;
    private javax.swing.JLabel title;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
