/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TokoFarda;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

public class menuDataSupplier extends javax.swing.JPanel {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    private DefaultTableModel model;
    private Timer timer;

    public menuDataSupplier() {
        initComponents();

        conn = Koneksi.Koneksi.KoneksiDB();

        //memberi penamaan pada judul kolom
        model = new DefaultTableModel();
        tb_Supplier.setModel(model);
        model.addColumn("Nama Supplier");
        model.addColumn("No Telpon");
        model.addColumn("Alamat");

        //membuat timer dengan delay 1000ms (1 dt) dan AcctionListener yang mempengaruhi label
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                showDayDateTime();
            }
        });

        timer.start();
        getData();
    }

    void getData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        try {
            //membuat statement pemanggilan data tabel barang dari database
            String sql = "select * from supplier order by id_Supplier ASC";

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            //penelusuran baris pada tabel barang dari database
            while (rs.next()) {
                Object[] obj = new Object[3];
                obj[0] = rs.getString("Nama_Supplier");
                obj[1] = rs.getString("No_Telp");
                obj[2] = rs.getString("Alamat");

                model.addRow(obj);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    void PilihData() {
        int i = tb_Supplier.getSelectedRow();

        //mengambil id supplier berdasarkan data yang dipilih
        String sql1 = "select * from supplier where Nama_Supplier='" + model.getValueAt(i, 0).toString() + "'";
        String idSupplier = "";
        try {
            pst = conn.prepareStatement(sql1);
            rs = pst.executeQuery();

            if (rs.next()) {
                session.setIdSupplier(rs.getString("Id_Supplier"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        txt_NamaSupplier.setText(model.getValueAt(i, 0).toString());
        txt_NoTelp.setText(model.getValueAt(i, 1).toString());
        txt_Alamat.setText(model.getValueAt(i, 2).toString());
    }

    void Bersih() {
        txt_NamaSupplier.setText("");
        txt_NoTelp.setText("");
        txt_Alamat.setText("");
        txt_cari.setText("Cari...");
    }

    private void showDayDateTime() {
        Calendar calendar = Calendar.getInstance();
        Date now = new Date();
        SimpleDateFormat formatHari = new SimpleDateFormat("EEEE", new Locale("in", "ID"));
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String hari = formatHari.format(calendar.getTime());
        String dateTime = dateFormat.format(now);
        lb_tanggal.setText(hari + ", " + dateTime);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        lb_tanggal = new javax.swing.JLabel();
        Nama_supplier = new javax.swing.JLabel();
        txt_NamaSupplier = new javax.swing.JTextField();
        No_telepon = new javax.swing.JLabel();
        txt_NoTelp = new javax.swing.JTextField();
        Alamat = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Alamat = new javax.swing.JTextArea();
        btn_edit = new rojerusan.RSMaterialButtonRectangle();
        btn_hapus = new rojerusan.RSMaterialButtonRectangle();
        btn_refresh = new rojerusan.RSMaterialButtonRectangle();
        btn_tambah = new rojerusan.RSMaterialButtonRectangle();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Supplier = new javax.swing.JTable();
        txt_cari = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1170, 750));

        header.setBackground(new java.awt.Color(237, 237, 237));

        title.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        title.setText("Menu Data Supplier");

        lb_tanggal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_tanggal.setText("Hari, Tanggal, Jam");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 766, Short.MAX_VALUE)
                .addComponent(lb_tanggal)
                .addGap(48, 48, 48))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(title)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_tanggal)
                .addContainerGap())
        );

        Nama_supplier.setText("Nama Supplier");

        No_telepon.setText("No Telepon");

        Alamat.setText("Alamat");

        txt_Alamat.setColumns(20);
        txt_Alamat.setRows(5);
        jScrollPane2.setViewportView(txt_Alamat);

        btn_edit.setBackground(new java.awt.Color(255, 255, 0));
        btn_edit.setForeground(new java.awt.Color(0, 0, 0));
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_hapus.setBackground(new java.awt.Color(255, 0, 0));
        btn_hapus.setForeground(new java.awt.Color(0, 0, 0));
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_refresh.setBackground(new java.awt.Color(102, 255, 102));
        btn_refresh.setForeground(new java.awt.Color(0, 0, 0));
        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        btn_tambah.setBackground(new java.awt.Color(51, 204, 255));
        btn_tambah.setForeground(new java.awt.Color(0, 0, 0));
        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        tb_Supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_Supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_SupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Supplier);

        txt_cari.setText("Cari...");
        txt_cari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cariFocusLost(evt);
            }
        });
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cariKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Nama_supplier)
                        .addComponent(txt_NoTelp)
                        .addComponent(No_telepon)
                        .addComponent(Alamat)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_NamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Nama_supplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_NamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(No_telepon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_NoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Alamat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 174, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tb_SupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_SupplierMouseClicked
        PilihData();
    }//GEN-LAST:event_tb_SupplierMouseClicked

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed

        if (txt_NamaSupplier.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harap isi nama supplier!!");
        } else if (txt_NoTelp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harap isi nomor telp supplier!!");
        } else if (txt_Alamat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harap isi alamat supplier!!");
        } else {
            try {
                Long.parseLong(txt_NoTelp.getText());
                try {
                    String NamaSupplier = txt_NamaSupplier.getText();
                    String noTelp = txt_NoTelp.getText();
                    String Alamat = txt_Alamat.getText();

                    String sql = "update supplier set Nama_Supplier='" + NamaSupplier + "',No_Telp='" + noTelp + "',Alamat='" + Alamat + "'where id_Supplier='" + session.getIdSupplier() + "'";
                    pst = conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                getData();
                Bersih();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Harap Masukan Angka Dengan Benar");
            }
        }
        
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null,
                "Apakah benar-benar akan dihapus permanen?",
                "Delete",
                JOptionPane.YES_NO_OPTION
        );
        if (p == 0) {
            String sql = "delete from supplier where id_Supplier='" + session.getIdSupplier() + "'";
            try {
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        getData();
        Bersih();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        Bersih();
        getData();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed

        if (txt_NamaSupplier.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harap isi nama supplier!!");
        } else if (txt_NoTelp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harap isi nomor telp supplier!!");
        } else if (txt_Alamat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harap isi alamat supplier!!");
        } else {
            try {
                Long.parseLong(txt_NoTelp.getText());
                String noTelp = txt_NoTelp.getText();

                try {
                    String sql = "insert into supplier (Nama_Supplier,No_Telp,Alamat)values(?,?,?)";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, txt_NamaSupplier.getText());
                    pst.setString(2, noTelp);
                    pst.setString(3, txt_Alamat.getText());

                    pst.execute();
                        JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                getData();
                Bersih();
                
            } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Harap Masukan Angka Dengan Benar");
            }
        }
        
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void txt_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyTyped
        // TODO add your handling code here:
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        try {
            String sql = "select * from supplier where Nama_Supplier like '%" + txt_cari.getText() + "%'";

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                Object[] obj = new Object[3];
                obj[0] = rs.getString("Nama_Supplier");
                obj[1] = rs.getString("No_Telp");
                obj[2] = rs.getString("Alamat");

                model.addRow(obj);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txt_cariKeyTyped

    private void txt_cariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariFocusGained
        // TODO add your handling code here:
        String cari = txt_cari.getText();
        if (cari.equals("Cari...")) {
            txt_cari.setText("");
        }
    }//GEN-LAST:event_txt_cariFocusGained

    private void txt_cariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariFocusLost
        // TODO add your handling code here:
        String cari = txt_cari.getText();
        if (cari.equals("") || cari.equals("Cari...")) {
            txt_cari.setText("Cari...");
        }
    }//GEN-LAST:event_txt_cariFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel Nama_supplier;
    private javax.swing.JLabel No_telepon;
    private rojerusan.RSMaterialButtonRectangle btn_edit;
    private rojerusan.RSMaterialButtonRectangle btn_hapus;
    private rojerusan.RSMaterialButtonRectangle btn_refresh;
    private rojerusan.RSMaterialButtonRectangle btn_tambah;
    private javax.swing.JPanel header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_tanggal;
    private javax.swing.JTable tb_Supplier;
    private javax.swing.JLabel title;
    private javax.swing.JTextArea txt_Alamat;
    private javax.swing.JTextField txt_NamaSupplier;
    private javax.swing.JTextField txt_NoTelp;
    private javax.swing.JTextField txt_cari;
    // End of variables declaration//GEN-END:variables
}
